# Generated by Django 3.0.6 on 2020-06-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeam', models.CharField(choices=[('Arsenal', 'Arsenal'), ('Aston Villa', 'Aston Villa'), ('Burnley', 'Burnley'), ('Brighton', 'Brighton'), ('Bournemouth', 'Bournemouth'), ('Chelsea', 'Chelsea'), ('Crystal Palace', 'Crystal Palace'), ('Everton', 'Everton'), ('Liverpool', 'Liverpool'), ('Leicester', 'Leicester'), ('Newcastle', 'Newcastle'), ('Man City', 'Man City'), ('Man Utd', 'Man Utd'), ('Norwich', 'Norwich'), ('Wolves', 'Wolves'), ('Sheffield Utd', 'Sheffield Utd'), ('Spurs', 'Spurs'), ('Southampton', 'Southampton'), ('Watford', 'Watford'), ('West Ham', 'West Ham')], max_length=15)),
                ('awayteam', models.CharField(choices=[('Arsenal', 'Arsenal'), ('Aston Villa', 'Aston Villa'), ('Burnley', 'Burnley'), ('Brighton', 'Brighton'), ('Bournemouth', 'Bournemouth'), ('Chelsea', 'Chelsea'), ('Crystal Palace', 'Crystal Palace'), ('Everton', 'Everton'), ('Liverpool', 'Liverpool'), ('Leicester', 'Leicester'), ('Newcastle', 'Newcastle'), ('Man City', 'Man City'), ('Man Utd', 'Man Utd'), ('Norwich', 'Norwich'), ('Wolves', 'Wolves'), ('Sheffield Utd', 'Sheffield Utd'), ('Spurs', 'Spurs'), ('Southampton', 'Southampton'), ('Watford', 'Watford'), ('West Ham', 'West Ham')], max_length=15)),
                ('homegoals', models.IntegerField()),
                ('awaygoals', models.IntegerField()),
            ],
        ),
    ]
