# Generated by Django 3.0.6 on 2020-07-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglandFixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('hometeam', models.CharField(max_length=25)),
                ('awayteam', models.CharField(max_length=25)),
                ('homegoals', models.IntegerField()),
                ('awaygoals', models.IntegerField()),
            ],
        ),
    ]
