# Generated by Django 3.0.6 on 2020-07-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_auto_20200708_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GermanyFixtures',
            new_name='GermanFixtures',
        ),
    ]
